# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: dasht 0.1.4 ruby lib

Gem::Specification.new do |s|
  s.name = "dasht"
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Rusty Klophaus"]
  s.date = "2015-08-11"
  s.description = "Dasht is a framework for building beautiful, developer-focused application dashboards. Dasht is especially good at displaying high-level application stats in real-time on a wall-mounted monitor."
  s.email = "rklophaus@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".agignore",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "NOTES.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "assets/css/style.css",
    "assets/js/Chart.min.js",
    "assets/js/dasht.js",
    "assets/js/jquery-1.11.3.min.js",
    "assets/js/mustache.min.js",
    "assets/js/underscore-min.js",
    "assets/plugins/chart.css",
    "assets/plugins/chart.html",
    "assets/plugins/chart.js",
    "assets/plugins/map.css",
    "assets/plugins/map.html",
    "assets/plugins/map.js",
    "assets/plugins/value.css",
    "assets/plugins/value.html",
    "assets/plugins/value.js",
    "dasht.gemspec",
    "examples/simple_heroku_dashboard.rb",
    "examples/simple_heroku_dashboard_2.rb",
    "lib/dasht.rb",
    "lib/dasht/array_monkeypatching.rb",
    "lib/dasht/base.rb",
    "lib/dasht/board.rb",
    "lib/dasht/list.rb",
    "lib/dasht/log_thread.rb",
    "lib/dasht/metric.rb",
    "lib/dasht/metrics.rb",
    "lib/dasht/rack_app.rb",
    "lib/dasht/reloader.rb",
    "screenshot_1.png",
    "test/helper.rb",
    "test/test_list.rb",
    "test/test_metric.rb",
    "views/dashboard.erb"
  ]
  s.homepage = "http://github.com/rustyio/dasht"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "Simple, beautiful, full-screen dashboards."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, ["~> 1.6"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, ["~> 3"])
    else
      s.add_dependency(%q<rack>, ["~> 1.6"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<test-unit>, ["~> 3"])
    end
  else
    s.add_dependency(%q<rack>, ["~> 1.6"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<test-unit>, ["~> 3"])
  end
end

